### ISSUE TITLE
docs: describe defprocotol+

### ISSUE THREAD

**Issue by lread** [clj-commons/potemkin#67]
Potemkin includes `defprotocol+` but the README does not make mention of it.

A recent conversation on slack reminded me I moved from an inlined version of `defprotocol+` to `defprotocol` when merging rewrite-clj v0 and rewrite-cljs v0 to create rewrite-clj v1. 

At the time I, wrongly, assumed `defprotocol+` was somehow related to performance. Maybe I was swayed by the `definterface+` description mentioning "time and memory". I dunno.

@dpsutton kindly helped me to understand that `defprotocol+` is about REPL reload friendliness and deals with [this kind of scenario](https://nelsonmorris.net/2015/05/18/reloaded-protocol-and-no-implementation-of-method.html).

I'd be happy to add a few words in the README about this with the sentiment that it is something that would have helped me understand, so it will probably help others.

**Comment by KingMob** [comment]
👍🏻 PR?

**Comment by lread** [comment]
Looks like I did one! #69 
I was hoping somebody could review it for correctness/completeness before merging.

**Comment by lread** [comment]
@KingMob are your comments implying that you are becoming a maintainer for this project? :crossed_fingers:

**Comment by KingMob** [comment]
Well, sort of... Would you like to maintain it?

I originally just wanted to maintain Manifold, which I was using heavily at the time. Then we needed to make some changes to Aleph, and I started maintaining that, too. Ditto for gloss, byte-streams, byte-transforms, etc. All of Tellman's old libraries.

However, I'm personally reluctant to do too much to potemkin. Mostly because it's in widespread use, especially `import-vars`. For now, I'm mostly interested in updating docs, adding kondo support where possible, and maybe deprecating things that no longer make sense (like clj-tuple, fast-memoize, etc)

**Comment by lread** [comment]
I'm not offended by the idea of importing vars, if Clojure core had such a feature I would likely use it. But because importing vars is not a core feature, tooling support is hit and miss, which for me, makes it impractical and too costly to use.

Anyhoo, it is nice to have someone looking at PRs and issues for potemkin, thanks for that! :heart:

**Comment by KingMob** [comment]
> I'm not offended by the idea of importing vars, if Clojure core had such a feature I would likely use it.

Yeah. Shame it's effectively impossible to change core. There are real limits to what you can do with an outside library.

**Comment by lread** [comment]
The arguments for and against the concept seem reasonable to me.
I'm fine with going with the core team flow here.
